modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
license="GNU LGPLv3"
issueTrackerURL="https://github.com/Darkorg69/GlobalBlockHardness/issues" #optional

[[mods]] #mandatory
modId="globalblockhardness" #mandatory
version="1.0.0-1.18.2" #mandatory
displayName="Global Block Hardness" #mandatory
#updateJSONURL="" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/global-block-hardness" #optional
logoFile="globalblockhardness.png" #optional
credits="Thanks for this mod goes to Java and the Forge team." #optional
# A text field displayed in the mod UI
authors="Darkorg" #optional
description='''This mod makes breaking blocks harder.'''

[[dependencies.globalblockhardness]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.globalblockhardness]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
